export const orgzlyI18n_overdue = new Map([
  ["default", "Overdue"],
  ["tr", "Süresi geçmiş"],
  ["ja", "期限切れ"],
  ["nl", "Achterstallig"],
  ["zh-tw", "逾期"],
  ["cs", "Po termínu"],
  ["lt", "Praleista"],
  ["hu", "Lejárt"],
  ["ko", "Overdue"],
  ["fr", "En retard"],
  ["es", "Atrasado"],
  ["uk", "Прострочено"],
  ["it", "Scaduto"],
  ["pt", "Em atraso"],
  ["ru", "Просрочено"],
  ["pl", "Zaległe"],
  ["sv", "Förfallen"],
  ["ar", "متأخر"],
  ["zh-cn", "过期"],
  ["pt-br", "Em atraso"],
  ["de", "Überfällig"],
  ["be", "Пратэрмінавана"],
])
